### ISSUE TITLE
error cdn

### ISSUE THREAD

**Issue by ryznxx** [SazumiVicky/sazumi-copilot#1]
# out of context

jadi gini bang, cdn lu error?? errornya gini pas gw test pake postman :

```html
<body>
    <pre>MulterError: Unexpected field<br> &nbsp; &nbsp;at wrappedFileFilter (/app/node_modules/multer/index.js:40:19)<br> &nbsp; &nbsp;at Multipart.&lt;anonymous&gt; (/app/node_modules/multer/lib/make-middleware.js:107:7)<br> &nbsp; &nbsp;at Multipart.emit (node:events:520:28)<br> &nbsp; &nbsp;at Multipart.emit (node:domain:488:12)<br> &nbsp; &nbsp;at HeaderParser.cb (/app/node_modules/busboy/lib/types/multipart.js:358:14)<br> &nbsp; &nbsp;at HeaderParser.push (/app/node_modules/busboy/lib/types/multipart.js:162:20)<br> &nbsp; &nbsp;at SBMH.ssCb [as _cb] (/app/node_modules/busboy/lib/types/multipart.js:394:37)<br> &nbsp; &nbsp;at feed (/app/node_modules/streamsearch/lib/sbmh.js:248:10)<br> &nbsp; &nbsp;at SBMH.push (/app/node_modules/streamsearch/lib/sbmh.js:104:16)<br> &nbsp; &nbsp;at Multipart._write (/app/node_modules/busboy/lib/types/multipart.js:567:19)</pre>
</body>
```

**Comment by SazumiVicky** [comment]
Semua service berjalan dengan normal, api juga normal

**Comment by ryznxx** [comment]
kalo dari kode work bang

```js
import fetch from "node-fetch";
import FormData from "form-data";
import fs from "fs";

async function sazumiCdn(filePath) {
  const formData = new FormData();
  formData.append("fileInput", fs.createReadStream(filePath));

  try {
    const response = await fetch("https://cdn.sazumi.moe/upload", {
      method: "POST",
      body: formData,
      headers: {
        ...formData.getHeaders(),
      },
    });

    if (response.ok) {
      const fileUrl = await response.json();
      console.log("Successfully uploaded:", fileUrl);
    } else {
      const errorResponse = await response.json();
      console.error("Oops, something went wrong:", errorResponse);
    }
  } catch (error) {
    console.error("Oops, something went wrong:", error.message);
  }
}

sazumiCdn("./src/image.jpg");

```
